import { useEffect, useState } from 'react'

const projects = [
    { id: 'casa-mh-residencial', title: 'Casa MH — Diseño residencial', category: 'Residencial', tag: 'Materia · Volumen', area: '280 m²', location: 'Valencia, ES', image: '/proyecto-1.jpg' },
    { id: 'casa-mh-interior', title: 'Casa MH — Vista interior', category: 'Interiorismo', tag: 'Luz · Habitar', area: '280 m²', location: 'Valencia, ES', image: '/proyecto-2.jpg' },
    { id: 'departamento-interior', title: 'Departamento — Diseño interior', category: 'Interiorismo', tag: 'Textura · Detalle', area: '125 m²', location: 'Barcelona, ES', image: '/proyecto-3.jpg' },
    { id: 'vivienda-cm-residencial', title: 'Vivienda CM — Proyecto residencial', category: 'Residencial', tag: 'Proporción · Luz', area: '190 m²', location: 'Madrid, ES', image: '/proyecto-4.jpg' },
    { id: 'casa-mh-frontal', title: 'Casa MH — Vista frontal', category: 'Proyectos', tag: 'Paisaje · Sombra', area: '340 m²', location: 'Sevilla, ES', image: '/proyecto-5.jpg' },
    { id: 'vivienda-cm-interior', title: 'Vivienda CM — Diseño interior', category: 'Interiorismo', tag: 'Calma · Materia', area: '190 m²', location: 'Madrid, ES', image: '/proyecto-6.jpg' }
]

function Header({ openMenu, setOpenMenu }) {
  return <header className="header"><a className="logo" href="#inicio" aria-label="ARKHE STUDIO, inicio"><img src="/arkhe-logo.svg" alt="ARKHE STUDIO" /></a><button className="menu-toggle" onClick={() => setOpenMenu(!openMenu)} aria-label="Menú">☰</button><nav className={openMenu ? 'nav open' : 'nav'}>{['Inicio','Sobre Nosotros','Servicios','Estimaciones','Proyectos','Contacto'].map((item) => <a key={item} href={`#${item === 'Inicio' ? 'inicio' : item.toLowerCase().replaceAll(' ','-')}`} onClick={() => setOpenMenu(false)}>{item}</a>)}</nav></header>
}

function SectionLabel({ number, children, light = false }) { return <div className={`section-label ${light ? 'light' : ''}`}><span>{number}</span><span>{children}</span></div> }

function ServiceIcon({ type }) {
  const common = { width: 52, height: 52, viewBox: '0 0 52 52', fill: 'none', xmlns: 'http://www.w3.org/2000/svg', 'aria-hidden': true }
  if (type === 'architecture') return <svg {...common}><path d="M8 43h36M12 43V22l14-11 14 11v21M19 43V29h14v14M8 22h36" stroke="currentColor" strokeWidth="1.5" /><path d="M26 11V5M22 7h8" stroke="currentColor" strokeWidth="1.5" /></svg>
  if (type === 'interior') return <svg {...common}><rect x="9" y="9" width="34" height="34" rx="17" stroke="currentColor" strokeWidth="1.5" /><path d="M17 34c5-7 10-11 18-16M17 19h8M31 34h4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /><circle cx="20" cy="19" r="3" stroke="currentColor" strokeWidth="1.5" /></svg>
  if (type === 'supervision') return <svg {...common}><path d="M10 39 22 27l8 8 13-18" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /><path d="M35 17h8v8M10 44h34" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /><circle cx="22" cy="27" r="3" fill="currentColor" /></svg>
  return <svg {...common}><path d="M12 40V12h28v28H12Z" stroke="currentColor" strokeWidth="1.5" /><path d="M18 33h16M18 26h16M18 19h8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /><path d="M33 18h3" stroke="currentColor" strokeWidth="1.5" /></svg>
}

function App() {
  const [openMenu, setOpenMenu] = useState(false)
  const [filter, setFilter] = useState('Todos')
  const [selected, setSelected] = useState(null)
  const [sent, setSent] = useState(false)
  useEffect(() => { const onKey = e => e.key === 'Escape' && setSelected(null); window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [])
  const visible = filter === 'Todos' ? projects : projects.filter(project => project.category === filter)
  return <>
    <Header openMenu={openMenu} setOpenMenu={setOpenMenu} />
    <main>
      <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">Estudio de arquitectura · 2024</p><h1>Soluciones arquitectónicas <i>&</i><br />estimación de alta precisión.</h1><p>Diseñamos espacios que fusionan innovación, función y belleza atemporal.</p><a className="button light-button" href="#proyectos">Explorar proyectos <b>↗</b></a></div><div className="hero-bottom">01 / 04 <span /> Scroll para descubrir</div><a className="scroll" href="#sobre-nosotros">↓</a></section>
      <section className="section intro" id="sobre-nosotros"><SectionLabel number="01">Estudio</SectionLabel><div className="intro-grid"><img src="/nosotros.jpg" alt="Interior contemporáneo" /><div><p className="eyebrow">Nuestra mirada</p><h2>El espacio como una forma de <i>habitar.</i></h2><p>En ARKHE STUDIO entendemos la arquitectura como un diálogo entre la luz, la materia y las personas. Cada proyecto nace de escuchar su contexto y traducirlo en espacios honestos, precisos y duraderos.</p><p>Trabajamos en arquitectura residencial e interiorismo con una mirada sensible al detalle. Diseñamos atmósferas que se sienten tan bien como se ven.</p><a className="text-link" href="#servicios">Conoce nuestra metodología ↗</a></div></div></section>
      <section className="section services" id="servicios"><div className="section-heading"><SectionLabel number="02">Lo que hacemos</SectionLabel><h2>Una visión integral<br /><i>para cada escala.</i></h2></div><div className="service-grid">{[['architecture','Proyecto Arquitectónico','Del concepto a los planos ejecutivos, construimos una visión coherente y habitable.'],['interior','Diseño de Interiores & Styling','Materiales, luz y piezas que convierten cada ambiente en una experiencia única.'],['supervision','Supervisión y Dirección de Obra','Coordinación rigurosa para que la idea se materialice con el estándar esperado.'],['estimate','Estimaciones y Presupuestos','Datos claros para tomar decisiones inteligentes desde el primer día.']].map(([icon,title,copy], i) => <article className="service-card" key={title}><small>0{i+1}</small><div className="icon"><ServiceIcon type={icon} /></div><h3>{title}</h3><p>{copy}</p><a href="#contacto" aria-label={`Contactar sobre ${title}`}>↗</a></article>)}</div></section>
      <section className="estimate" id="estimaciones"><SectionLabel number="03" light>Precisión que construye</SectionLabel><div className="estimate-grid"><h2>El control del presupuesto también es <i>diseño.</i></h2><div><p>Analizamos cada partida, material y fase para que el presupuesto sea una herramienta real de control, no una promesa.</p><a className="button light-button" href="#contacto">Solicitar una estimación <b>↗</b></a></div></div><div className="stats"><div><strong>+120</strong><span>proyectos analizados</span></div><div><strong>98%</strong><span>de precisión media</span></div><div><strong>15</strong><span>años de experiencia</span></div></div></section>
      <section className="section projects" id="proyectos"><div className="projects-heading"><div><SectionLabel number="04">Selección de obra</SectionLabel><h2>Proyectos<br /><i>con intención.</i></h2></div><p>Una selección de espacios donde la materia, la luz y la proporción encuentran su equilibrio.</p></div><div className="filters">{['Todos','Residencial','Interiorismo','Proyectos'].map(item => <button className={filter === item ? 'active' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="project-grid">{visible.map(project => <article className="project-card" key={project.id} onClick={() => setSelected(project)}><img src={project.image} alt={project.title} /><div className="project-overlay"><small>{project.category} · {project.tag}</small><h3>{project.title}</h3><span>Ver proyecto ↗</span></div></article>)}</div></section>
      <section className="section contact" id="contacto"><SectionLabel number="05">Hablemos</SectionLabel><div className="contact-grid"><div><h2>Hagamos espacio<br />para una nueva <i>idea.</i></h2><p>Cuéntanos sobre tu proyecto. Nos encantará escucharlo y encontrar la mejor forma de hacerlo realidad.</p><div className="details"><a href="mailto:jpulido@archestimastudio.com">jpulido@archestimastudio.com</a><a href="tel:+524525002106">+52 452 500 2106</a><span>Ciudad de México · México</span></div></div><form onSubmit={e => { e.preventDefault(); setSent(true); e.target.reset() }}><label>Nombre<input required placeholder="Tu nombre" /></label><label>Correo electrónico<input required type="email" placeholder="tu@email.com" /></label><label>Teléfono<input type="tel" placeholder="+52 000 000 0000" /></label><label>Mensaje<textarea required rows="3" placeholder="Cuéntanos sobre tu proyecto" /></label><button className="button dark-button">Enviar mensaje <b>↗</b></button>{sent && <p className="success">Gracias. Hemos recibido tu mensaje.</p>}</form></div></section>
      <section className="pre-footer"><div><SectionLabel number="06">Hablemos de tu proyecto</SectionLabel><h2>Te ayudamos a materializar el diseño perfecto o a obtener estimaciones de máxima precisión para tu obra.</h2></div><div className="pre-footer-contact"><a href="tel:+524525002106">+52 452 500 2106</a><a href="mailto:jpulido@archestimastudio.com">jpulido@archestimastudio.com</a><div><span>Follow us</span><a href="https://instagram.com" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://linkedin.com" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></section>
    </main>
      <footer><a className="logo" href="#inicio" aria-label="ARKHE STUDIO, inicio"><img src="/arkhe-logo.svg" alt="ARKHE STUDIO" /></a><nav><a href="#sobre-nosotros">Estudio</a><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a><a href="#contacto">Contacto</a></nav><small>© 2024 ARKHE STUDIO. Todos los derechos reservados.</small></footer>
    {selected && <div className="modal" onClick={() => setSelected(null)}><div className="modal-content" onClick={e => e.stopPropagation()}><button onClick={() => setSelected(null)} aria-label="Cerrar">×</button><img src={selected.image} alt={selected.title} /><div><p className="eyebrow">{selected.category} · {selected.tag}</p><h2>{selected.title}</h2><p>Una propuesta de arquitectura que combina materialidad, luz y proporción para construir una experiencia atemporal.</p><div className="modal-specs"><span><b>Ubicación</b>{selected.location}</span><span><b>Superficie</b>{selected.area}</span><span><b>Año</b>2024</span></div></div></div></div>}
  </>
}
export default App
